Employee active ui
bhushan-oe/EMS pull request #23
Opened 2020-03-30 04:54 UTC by surekhag

2020-03-30 06:58 UTC, bhushan-oe requested changes

2020-03-30 06:58 UTC, bhushan-oe commented on client/src/api/employeeApi.js
> +   console.log("in api", data)
remove console

2020-03-30 06:58 UTC, bhushan-oe commented on client/src/sagas/watchers/employeeInfo.js
> +      console.log("active",employees)
remove console

2020-03-30 06:58 UTC, bhushan-oe commented on client/src/sagas/watchers/employeeInfo.js
> +       console.log('all',employees)
remove console

2020-03-30 06:59 UTC, bhushan-oe commented
run eslint and format. resolve conflicts

2020-04-07 10:49 UTC, surekhag commented
We donr need this code anymore ..

2020-04-07 10:49 UTC, closed without merging