Employee listing disabled button for inactive employee, sort according status
bhushan-oe/EMS pull request #39
Opened 2020-04-09 09:16 UTC by AatishBondge

…cording to active and inactive

2020-04-09 09:51 UTC, bhushan-oe requested changes

2020-04-09 09:51 UTC, bhushan-oe commented on client/src/components/Employee/EmployeeListTable.js
> +  tableData.sort((a, b) =>
Sort data at Server side.

2020-04-09 10:06 UTC, AatishBondge commented on client/src/components/Employee/EmployeeListTable.js
> +  tableData.sort((a, b) =>
done

2020-04-14 05:18 UTC, bhushan-oe approved these changes

2020-04-14 05:18 UTC, merged