[EMS] EmployeeListing Code Refactoring
bhushan-oe/EMS pull request #45
Opened 2020-04-16 05:25 UTC by shivamsharma30

2020-04-16 06:13 UTC, bhushan-oe requested changes

2020-04-16 06:13 UTC, bhushan-oe commented on client/src/components/AddEmployeeForm/subcomponents/InputFields.js
> +                type={name === 'password' && 'password'}
default type should be 'text'

2020-04-16 11:08 UTC, shivamsharma30 commented on client/src/components/AddEmployeeForm/subcomponents/InputFields.js
> +                type={name === 'password' && 'password'}
Done

2020-04-21 11:26 UTC, bhushan-oe approved these changes

2020-04-21 11:26 UTC, merged